version: "3.8"

services:
  postgres:
    image: docker.io/library/postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: techcrm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: docker.io/library/redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
